services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://hetalmangukia:postgres@db:5432/postgres
      TEST_DATABASE_URL: postgresql://hetalmangukia:postgres@db:5432/postgres_test
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: hetalmangukia
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  redis: 
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  ruff:
    image: ghcr.io/astral-sh/ruff:latest
    volumes:
      - .:/code
    working_dir: /code
