"""updated some db fields for optimization

Revision ID: 7997b0679d41
Revises: c000b7419d4b
Create Date: 2025-07-16 23:23:55.505090

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "7997b0679d41"
down_revision: Union[str, Sequence[str], None] = "c000b7419d4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
