"""updated slug and long_url fields of URL

Revision ID: c000b7419d4b
Revises: 78c8ce3727e2
Create Date: 2025-07-16 20:09:48.430737

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c000b7419d4b"
down_revision: Union[str, Sequence[str], None] = "78c8ce3727e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_url_long_url"), "url", ["long_url"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_url_long_url"), table_name="url")
    # ### end Alembic commands ###
